			<p>The page you have requested cannot be found.</p>

			<p>This message has been generated by the Welcome controller located here:</p>

			<pre><code><?php echo $controller_file; ?></code></pre>

			<p>To edit this 404 page, you can edit the following file:</p>

			<pre><code><?php echo Fuel::clean_path(__FILE__); ?></code></pre>

			<p></p>