<?php
/**
 * Set all the paths
 */
$app_path		= '../fuel/app/';
$package_path	= '../fuel/packages/';
$core_path		= '../fuel/core/';

/**
 * If you your server does not have a default timezone set, E_WARNING messages will be generated by PHP.  To resolve this
 * issue uncomment this line and change the timezone to fit your needs.
 */
//date_default_timezone_set('UTC');

/**
 * Define the internal encoding to use.
 *
 * @todo Re-evaluate how to handle this.
 */
define('INTERNAL_ENC', 'ISO-8859-1');

// Load in the base, which initializes the framework and sets up some global functions.
is_file($app_path.'base.php') and require $app_path.'base.php';
require $core_path.'base.php';

// Initialize the framework
Fuel\App\Fuel::init();
Fuel\App\Request::factory()->execute()->send_headers()->output();
Fuel\App\Event::shutdown();
Fuel\App\Fuel::finish();

/* End of file index.php */