#!/usr/bin/php
<?php

// Start off by getting the base arguments;
list($filename, $action, $type) = array_pad($argv, 3, false);

if (strncmp($filename, './', 2) === 0)
{
	define('BASE', '..'.DIRECTORY_SEPARATOR);
	$template_path = 'templates'.DIRECTORY_SEPARATOR;
}
else
{
	define('BASE', '.'.DIRECTORY_SEPARATOR);
	$template_path = 'scripts'.DIRECTORY_SEPARATOR.'templates'.DIRECTORY_SEPARATOR;
}

switch($type)
{
	case 'controller':

		$path = BASE.'application'.DIRECTORY_SEPARATOR.'classes'.DIRECTORY_SEPARATOR.'controller'.DIRECTORY_SEPARATOR;
		$file = strtolower($argv[3]).'.php';

		if ($action == 'generate')
		{
			if ( ! is_writable(realpath($path)))
			{
				die($path.' is not writable.'.PHP_EOL);
			}

			$name = $argv[3];
			$content = file_get_contents($template_path.'controller.tpl');
			
			if (count($argv) > 4)
			{
				$action_tpl = file_get_contents($template_path.'action.tpl');
				$actions = '';
				
				for ($i = 4; $i < count($argv); $i++)
				{
					$action_name = substr($argv[$i], 1);
					$actions .= str_replace(array('{NAME}', '{ACTION}'), array($name, $action_name), $action_tpl).PHP_EOL.PHP_EOL;
					create_view($name.'/'.$action_name, '<h2>'.ucfirst($name).'</h2>'.PHP_EOL.'<p>'.ucfirst($action_name).'</p>');
				}
			}

			$content = trim(str_replace(array('{NAME}', '{ACTIONS}', '{FILENAME}', '{CLASS_NAME}'), array($name, rtrim($actions), $name.'.php', ucfirst($name)), $content));

			file_put_contents($path.$file, $content);
			chmod($path.$file, 0666);
			echo 'Controller '.$name.' has been created!'.PHP_EOL;
		}
		
	break;
}

function create_view($rel_path, $content)
{
	$views_path = BASE.DIRECTORY_SEPARATOR.'application'.DIRECTORY_SEPARATOR.'views'.DIRECTORY_SEPARATOR;
	$file = $views_path.$rel_path.'.php';

	$paths = explode(DIRECTORY_SEPARATOR, $rel_path);
	array_pop($paths);
	
	$curr_path = $views_path;
	foreach($paths as $path)
	{
		$curr_path .= $path.DIRECTORY_SEPARATOR;
		if ( ! is_dir($curr_path))
		{
			mkdir($curr_path, 0777);
			chmod($curr_path, 0777);
		}
	}

	file_put_contents($file, $content);
	chmod($file, 0666);
	echo 'View '.$rel_path.' has been created!'.PHP_EOL;
}